"""
Hood'd Design Pipeline v6 — Complete nation data for all 48 World Cup 2026 teams.
Each nation has flag colors, cultural motifs, jersey pattern descriptions,
landmark references, and content to avoid for legal/cultural safety.
"""

NATIONS = {
    # ── HOSTS ──────────────────────────────────────────────────────────────
    "USA": {
        "code": "us",
        "flag_colors": ["#B22234", "#FFFFFF", "#3C3B6E"],
        "accent": "#FFD700",
        "flag_pattern": "red and white horizontal stripes with a navy blue canton of white stars",
        "cultural_motifs": "eagle silhouette, bold stars scattered dynamically, sweeping stripes in motion, forward-momentum energy",
        "landmarks": "Statue of Liberty silhouette, Golden Gate Bridge outline, open highways",
        "jersey_pattern": "navy with white chest band, red accents, dynamic diagonal slash",
        "retro_era": "1994",
        "retro_desc": "denim blue with white stars and red stripes — the original World Cup host kit",
        "retro_colors": ["#002868", "#FFFFFF", "#BF0A30"],
        "avoid": "specific city skylines in detail, military imagery, Capitol building, political symbols",
    },
    "Canada": {
        "code": "ca",
        "flag_colors": ["#FF0000", "#FFFFFF"],
        "accent": "#000000",
        "flag_pattern": "vertical red-white-red bands with a red maple leaf centered on white",
        "cultural_motifs": "maple leaf in motion, northern lights aurora ribbons, mountain ridge silhouettes, hockey stick angles",
        "landmarks": "CN Tower silhouette, Rocky Mountain peaks, maple forests",
        "jersey_pattern": "red with white diagonal sash, maple leaf crest, black accents",
        "retro_era": "1986",
        "retro_desc": "bright red with white trim — Canada's first World Cup qualification kit",
        "retro_colors": ["#FF0000", "#FFFFFF", "#000000"],
        "avoid": "specific province flags, Indigenous sacred symbols without context, beaver stereotypes",
    },
    "Mexico": {
        "code": "mx",
        "flag_colors": ["#006847", "#FFFFFF", "#CE1126"],
        "accent": "#FFD700",
        "flag_pattern": "vertical green-white-red tricolor",
        "cultural_motifs": "Aztec calendar stone patterns, eagle and serpent silhouette, geometric step pyramids, Day of the Dead sugar skull motifs, feathered serpent curves",
        "landmarks": "Pyramid of the Sun outline, Aztec temple steps, agave plants",
        "jersey_pattern": "dark green with Aztec geometric pattern overlay, white and red accents",
        "retro_era": "1986",
        "retro_desc": "jade green with geometric Aztec shoulder pattern — Maradona's World Cup, Mexico hosting",
        "retro_colors": ["#006847", "#FFFFFF", "#CE1126"],
        "avoid": "sombrero stereotypes, specific cartel references, religious imagery of Virgin Mary",
    },
    # ── CONCACAF ───────────────────────────────────────────────────────────
    "Panama": {
        "code": "pa",
        "flag_colors": ["#FFFFFF", "#DA121A", "#003DA5"],
        "accent": "#FFD700",
        "flag_pattern": "quartered white-red and blue-white with blue and red stars",
        "cultural_motifs": "canal lock silhouettes, tropical bird wings, maritime navigation lines, bridge arches",
        "landmarks": "Panama Canal, Bridge of the Americas silhouette",
        "jersey_pattern": "red with diagonal white stripe, blue collar",
        "retro_era": "2018",
        "retro_desc": "red and white diagonal split — Panama's historic first World Cup",
        "retro_colors": ["#DA121A", "#FFFFFF", "#003DA5"],
        "avoid": "specific political references, drug trade imagery",
    },
    "Curaçao": {
        "code": "cw",
        "flag_colors": ["#002B7F", "#F9E814"],
        "accent": "#FFFFFF",
        "flag_pattern": "blue field with two yellow stars and horizontal yellow stripe",
        "cultural_motifs": "Caribbean ocean waves, floating bridge curves, tropical flora, pastel Handelskade facades, coral reef patterns",
        "landmarks": "Queen Emma Bridge, Handelskade waterfront colors, coral reefs",
        "jersey_pattern": "royal blue with yellow chest band, white accents",
        "retro_era": "2026",
        "retro_desc": "historic first World Cup — blue and yellow pride",
        "retro_colors": ["#002B7F", "#F9E814", "#FFFFFF"],
        "avoid": "Dutch colonial imagery, gambling references",
    },
    "Haiti": {
        "code": "ht",
        "flag_colors": ["#00209F", "#D21034"],
        "accent": "#FFFFFF",
        "flag_pattern": "horizontal blue over red bicolor",
        "cultural_motifs": "palm tree silhouettes, drums and rhythm lines, citadel fortress angles, veve sacred geometry patterns, tropical sunrise",
        "landmarks": "Citadelle Laferrière silhouette, tropical palm groves",
        "jersey_pattern": "blue and red split with white center band",
        "retro_era": "1974",
        "retro_desc": "blue and red halves — Haiti's World Cup golden era in Germany",
        "retro_colors": ["#00209F", "#D21034", "#FFFFFF"],
        "avoid": "voodoo stereotypes, earthquake imagery, poverty depictions",
    },
    # ── CONMEBOL ───────────────────────────────────────────────────────────
    "Argentina": {
        "code": "ar",
        "flag_colors": ["#74ACDF", "#FFFFFF", "#F6B40E"],
        "accent": "#000000",
        "flag_pattern": "horizontal sky blue and white stripes with golden Sun of May",
        "cultural_motifs": "Sun of May radiating beams, tango dance curves, gaucho lasso spirals, Andes mountain ridgelines",
        "landmarks": "Obelisco silhouette, Andes peaks, La Boca color blocks",
        "jersey_pattern": "sky blue and white vertical stripes, gold sun accent on chest",
        "retro_era": "1986",
        "retro_desc": "sky blue and white vertical stripes with v-neck — the Maradona kit",
        "retro_colors": ["#74ACDF", "#FFFFFF", "#000000"],
        "avoid": "Falklands/Malvinas political imagery, specific political figures",
    },
    "Brazil": {
        "code": "br",
        "flag_colors": ["#009C3B", "#FFDF00", "#002776"],
        "accent": "#FFFFFF",
        "flag_pattern": "green field with large yellow diamond and blue circle",
        "cultural_motifs": "carnival ribbons in motion, tropical bird silhouettes of toucan and macaw, samba rhythm curves, Christ the Redeemer silhouette",
        "landmarks": "Christ the Redeemer silhouette, Sugarloaf Mountain, Amazon canopy",
        "jersey_pattern": "canary yellow with green collar, blue accents, dynamic swoosh",
        "retro_era": "1970",
        "retro_desc": "vivid canary yellow with green collar — the Pelé era, greatest team ever",
        "retro_colors": ["#FFD700", "#009C3B", "#002776"],
        "avoid": "flag motto text, detailed globe from flag, favela imagery",
    },
    "Colombia": {
        "code": "co",
        "flag_colors": ["#FCD116", "#003893", "#CE1126"],
        "accent": "#FFFFFF",
        "flag_pattern": "horizontal yellow (double width), blue, and red bands",
        "cultural_motifs": "golden El Dorado sun discs, coffee plant branches, condor wings spread, cumbia dance motion, emerald facets",
        "landmarks": "Cartagena fortress walls, Andes condor, coffee mountains",
        "jersey_pattern": "bright yellow with blue collar and red trim, angular chest pattern",
        "retro_era": "1990",
        "retro_desc": "yellow with blue wave pattern — Valderrama's iconic Colombian flair",
        "retro_colors": ["#FCD116", "#003893", "#CE1126"],
        "avoid": "drug/cartel references, specific political imagery",
    },
    "Ecuador": {
        "code": "ec",
        "flag_colors": ["#FFD100", "#0038A8", "#CE1126"],
        "accent": "#FFFFFF",
        "flag_pattern": "horizontal yellow (double width), blue, and red bands",
        "cultural_motifs": "Andean condor wings, volcanic peaks, equatorial sun disc, woven textile patterns, Galápagos tortoise shell geometry",
        "landmarks": "Cotopaxi volcano, equatorial line monument, Galápagos islands",
        "jersey_pattern": "golden yellow with blue diagonal stripes, red accents",
        "retro_era": "2006",
        "retro_desc": "bright yellow with blue trim — Ecuador's breakthrough World Cup run",
        "retro_colors": ["#FFD100", "#0038A8", "#CE1126"],
        "avoid": "specific political imagery, detailed coat of arms",
    },
    "Paraguay": {
        "code": "py",
        "flag_colors": ["#DA121A", "#FFFFFF", "#0038A8"],
        "accent": "#FFD700",
        "flag_pattern": "horizontal red-white-blue triband",
        "cultural_motifs": "Guarani geometric textile patterns, harp strings, yerba mate leaf outlines, river delta curves, ñandutí lace patterns",
        "landmarks": "Itaipu Dam arches, Chaco plains, Paraguay River bends",
        "jersey_pattern": "red and white stripes with blue shorts accent",
        "retro_era": "2010",
        "retro_desc": "red and white stripes with blue collar — Paraguay's best World Cup showing",
        "retro_colors": ["#DA121A", "#FFFFFF", "#0038A8"],
        "avoid": "specific political references, war imagery",
    },
    "Uruguay": {
        "code": "uy",
        "flag_colors": ["#0038A8", "#FFFFFF", "#F6B40E"],
        "accent": "#000000",
        "flag_pattern": "nine horizontal blue and white stripes with golden Sun of May canton",
        "cultural_motifs": "Sun of May beams, four championship stars, Río de la Plata wave patterns, gaucho riding silhouette, candombe drum rhythms",
        "landmarks": "Estadio Centenario silhouette, Montevideo cityscape, coastal waves",
        "jersey_pattern": "sky blue with sun emblem, white collar, four stars above crest",
        "retro_era": "1930",
        "retro_desc": "sky blue — the very first World Cup champions on home soil",
        "retro_colors": ["#0038A8", "#FFFFFF", "#F6B40E"],
        "avoid": "specific political imagery",
    },
    # ── UEFA ───────────────────────────────────────────────────────────────
    "England": {
        "code": "gb-eng",
        "flag_colors": ["#FFFFFF", "#CE1124", "#002395"],
        "accent": "#FFD700",
        "flag_pattern": "white field with red cross of St George",
        "cultural_motifs": "three lions heraldic silhouette, Tudor rose, crown outline, Big Ben clock tower, double-decker bus angles",
        "landmarks": "Big Ben silhouette, Tower Bridge outline, Wembley arch",
        "jersey_pattern": "white with navy blue shoulder stripes, red collar accent",
        "retro_era": "1966",
        "retro_desc": "red with white trim — the only World Cup winning kit, Bobby Moore era",
        "retro_colors": ["#CE1124", "#FFFFFF", "#002395"],
        "avoid": "Union Jack (this is England not UK), specific royal family imagery",
    },
    "France": {
        "code": "fr",
        "flag_colors": ["#002395", "#FFFFFF", "#ED2939"],
        "accent": "#FFD700",
        "flag_pattern": "vertical blue-white-red tricolor",
        "cultural_motifs": "Gallic rooster silhouette, fleur-de-lis pattern, Eiffel Tower outline, Art Deco geometric flourishes, revolutionary tricolor ribbons",
        "landmarks": "Eiffel Tower silhouette, Arc de Triomphe outline, Parisian rooftops",
        "jersey_pattern": "navy blue with white and red chest stripe, gold accents",
        "retro_era": "1998",
        "retro_desc": "deep blue with subtle pinstripe — Zidane's World Cup winning masterpiece on home soil",
        "retro_colors": ["#002395", "#FFFFFF", "#ED2939"],
        "avoid": "specific wine/cheese stereotypes, Napoleonic military imagery",
    },
    "Germany": {
        "code": "de",
        "flag_colors": ["#000000", "#DD0000", "#FFCC00"],
        "accent": "#FFFFFF",
        "flag_pattern": "horizontal black-red-gold triband",
        "cultural_motifs": "Bundesadler eagle silhouette, Bauhaus geometric patterns, Brandenburg Gate outline, four championship stars, precision industrial lines",
        "landmarks": "Brandenburg Gate silhouette, Cologne Cathedral spires, autobahn infinity",
        "jersey_pattern": "white with black geometric chest pattern, red and gold accents",
        "retro_era": "1990",
        "retro_desc": "white with angular black-red-gold chest stripe — Matthäus World Cup winning kit",
        "retro_colors": ["#FFFFFF", "#000000", "#DD0000", "#FFCC00"],
        "avoid": "Iron Cross in isolation, Imperial German symbols, political references",
    },
    "Spain": {
        "code": "es",
        "flag_colors": ["#AA151B", "#F1BF00"],
        "accent": "#FFFFFF",
        "flag_pattern": "horizontal red-yellow-red with yellow band double width",
        "cultural_motifs": "bull silhouette in motion, flamenco fan curves, mosaic tile patterns, La Tomatina splatter energy, matador cape swirl",
        "landmarks": "Sagrada Familia spires, Alhambra arches, running bull silhouettes",
        "jersey_pattern": "red with yellow shoulder band, tiki-taka inspired geometric pattern",
        "retro_era": "2010",
        "retro_desc": "deep red with gold trim — the tiki-taka World Cup champions",
        "retro_colors": ["#AA151B", "#F1BF00", "#FFFFFF"],
        "avoid": "Osborne bull trademark (stylize differently), specific regional independence symbols",
    },
    "Portugal": {
        "code": "pt",
        "flag_colors": ["#006600", "#FF0000"],
        "accent": "#FFD700",
        "flag_pattern": "vertical green and red bicolor with coat of arms on the divide",
        "cultural_motifs": "navigation compass rose, Age of Discovery caravel sails, azulejo tile patterns, rooster of Barcelos, maritime rope knots",
        "landmarks": "Belém Tower silhouette, Ponte 25 de Abril bridge, Sintra castle spires",
        "jersey_pattern": "dark red with green collar, gold cross accent, diagonal green panel",
        "retro_era": "2006",
        "retro_desc": "burgundy red with green trim and gold shield — the Ronaldo breakout era",
        "retro_colors": ["#006600", "#FF0000", "#FFD700"],
        "avoid": "specific colonial references, religious imagery in detail",
    },
    "Netherlands": {
        "code": "nl",
        "flag_colors": ["#AE1C28", "#FFFFFF", "#21468B"],
        "accent": "#FF6600",
        "flag_pattern": "horizontal red-white-blue triband",
        "cultural_motifs": "Dutch orange lion rampant, tulip silhouettes in rows, windmill blade angles, canal water reflections, Delft blue tile patterns",
        "landmarks": "windmill silhouettes, Amsterdam canal houses, tulip fields",
        "jersey_pattern": "bright orange with white and black geometric, lion crest",
        "retro_era": "1974",
        "retro_desc": "bright orange with white collar and cuffs — Cruyff's Total Football revolution",
        "retro_colors": ["#FF6600", "#FFFFFF", "#000000"],
        "avoid": "marijuana/drug culture references, Red Light District imagery",
    },
    "Belgium": {
        "code": "be",
        "flag_colors": ["#000000", "#FDDA24", "#EF3340"],
        "accent": "#FFFFFF",
        "flag_pattern": "vertical black-yellow-red tricolor",
        "cultural_motifs": "Art Nouveau flowing lines, Atomium sphere clusters, chocolate swirl patterns, Manneken Pis silhouette, comic book panel energy",
        "landmarks": "Atomium spheres, Grand Place towers, Bruges canal bridges",
        "jersey_pattern": "red with black and yellow diagonal flash, devilish energy",
        "retro_era": "1986",
        "retro_desc": "red with Adidas stripes — Belgium's best World Cup, the Red Devils peak",
        "retro_colors": ["#EF3340", "#000000", "#FDDA24"],
        "avoid": "specific political/linguistic division references",
    },
    "Croatia": {
        "code": "hr",
        "flag_colors": ["#FF0000", "#FFFFFF", "#0000FF"],
        "accent": "#FFD700",
        "flag_pattern": "horizontal red-white-blue triband with checkerboard coat of arms",
        "cultural_motifs": "red and white checkerboard (šahovnica) pattern, Adriatic sea wave forms, Dalmatian coast cliff lines, medieval fortress walls",
        "landmarks": "Dubrovnik walls, Plitvice waterfalls, Zagreb cathedral spires",
        "jersey_pattern": "red and white checkerboard all-over, blue collar trim",
        "retro_era": "1998",
        "retro_desc": "red and white checkerboard — Šuker's team that took third on debut",
        "retro_colors": ["#FF0000", "#FFFFFF", "#0000FF"],
        "avoid": "specific war references, political symbols",
    },
    "Switzerland": {
        "code": "ch",
        "flag_colors": ["#FF0000", "#FFFFFF"],
        "accent": "#000000",
        "flag_pattern": "red field with bold white cross",
        "cultural_motifs": "white cross precision, Alpine peak silhouettes, watch gear mechanisms, Swiss knife geometry, edelweiss flower",
        "landmarks": "Matterhorn peak, Swiss Alps panorama, medieval clock towers",
        "jersey_pattern": "red with white cross motif, precision geometric lines",
        "retro_era": "2006",
        "retro_desc": "red with white Swiss cross — unbeaten in group stage, Swiss precision",
        "retro_colors": ["#FF0000", "#FFFFFF"],
        "avoid": "banking/money references, Nazi gold references",
    },
    "Austria": {
        "code": "at",
        "flag_colors": ["#ED2939", "#FFFFFF"],
        "accent": "#000000",
        "flag_pattern": "horizontal red-white-red triband",
        "cultural_motifs": "Alpine mountain ridge lines, Vienna waltz spiral curves, musical notation flow, Baroque ornamental swirls, ski track lines",
        "landmarks": "Vienna Opera House silhouette, Salzburg fortress, Alpine peaks",
        "jersey_pattern": "red with white chest panel, clean Austrian lines",
        "retro_era": "1982",
        "retro_desc": "red and white classic — Austrian football's World Cup heritage",
        "retro_colors": ["#ED2939", "#FFFFFF", "#000000"],
        "avoid": "specific Habsburg/Imperial references, WWII references",
    },
    "Norway": {
        "code": "no",
        "flag_colors": ["#BA0C2F", "#FFFFFF", "#00205B"],
        "accent": "#FFD700",
        "flag_pattern": "red field with blue cross outlined in white (Nordic cross)",
        "cultural_motifs": "Viking longship prow curves, Nordic knot patterns, aurora borealis ribbons, fjord cliff walls, runic angular geometry",
        "landmarks": "fjord silhouettes, Viking ship outlines, northern lights",
        "jersey_pattern": "red with blue and white Nordic cross accent, Viking energy",
        "retro_era": "1998",
        "retro_desc": "red with blue trim — Norway's last World Cup, beating Brazil in group stage",
        "retro_colors": ["#BA0C2F", "#FFFFFF", "#00205B"],
        "avoid": "specific religious Norse imagery (Thor's hammer as weapon), Black Metal references",
    },
    "Scotland": {
        "code": "gb-sct",
        "flag_colors": ["#003DA5", "#FFFFFF"],
        "accent": "#FFD700",
        "flag_pattern": "blue field with white diagonal saltire (St Andrew's cross)",
        "cultural_motifs": "tartan weave patterns, thistle silhouettes, Highland landscape ridges, Celtic knotwork, claymore sword angles",
        "landmarks": "Edinburgh Castle silhouette, Highland glens, Forth Bridge arches",
        "jersey_pattern": "navy blue with white saltire accent, tartan trim detail",
        "retro_era": "1998",
        "retro_desc": "dark blue with tartan trim — Scotland's passionate World Cup identity",
        "retro_colors": ["#003DA5", "#FFFFFF", "#FFD700"],
        "avoid": "Braveheart movie references, specific clan tartans, anti-English messaging",
    },
    "Sweden": {
        "code": "se",
        "flag_colors": ["#006AA7", "#FECC02"],
        "accent": "#FFFFFF",
        "flag_pattern": "blue field with yellow Nordic cross",
        "cultural_motifs": "yellow Nordic cross beams, three crowns heraldic, Viking rune stone patterns, Dala horse silhouette, midnight sun glow",
        "landmarks": "Stockholm palace, Nordic forests, Viking runestones",
        "jersey_pattern": "yellow with blue collar and sleeves, clean Scandinavian lines",
        "retro_era": "1994",
        "retro_desc": "bright yellow with blue — third place in USA, Scandinavian brilliance",
        "retro_colors": ["#FECC02", "#006AA7", "#FFFFFF"],
        "avoid": "specific political references, IKEA brand references",
    },
    "Turkey": {
        "code": "tr",
        "flag_colors": ["#E30A17", "#FFFFFF"],
        "accent": "#000000",
        "flag_pattern": "red field with white crescent moon and star",
        "cultural_motifs": "crescent moon arc, star bursts, Ottoman tulip patterns, Turkish carpet geometric weave, whirling dervish spiral, mosque dome curves",
        "landmarks": "Hagia Sophia dome, Blue Mosque minarets, Bosphorus bridge",
        "jersey_pattern": "red with white crescent and star motif, sharp angular design",
        "retro_era": "2002",
        "retro_desc": "red with white trim — Turkey's sensational third place in Korea/Japan",
        "retro_colors": ["#E30A17", "#FFFFFF"],
        "avoid": "specific political imagery, Armenian Genocide references, Kurdish conflict references",
    },
    "Bosnia and Herzegovina": {
        "code": "ba",
        "flag_colors": ["#002395", "#FFCD00", "#FFFFFF"],
        "accent": "#000000",
        "flag_pattern": "blue field with yellow triangle and diagonal line of white stars",
        "cultural_motifs": "Stećci medieval tombstone geometry, bridge arches, Bosnian lily (ljiljan), mountain silhouettes, river canyon curves",
        "landmarks": "Stari Most bridge arch, Sarajevo skyline, Bosnian mountains",
        "jersey_pattern": "blue with yellow diagonal stripe, white star accents",
        "retro_era": "2014",
        "retro_desc": "blue with diamond pattern — Bosnia's historic first World Cup",
        "retro_colors": ["#002395", "#FFCD00", "#FFFFFF"],
        "avoid": "war/conflict imagery, ethnic division references, specific religious symbols",
    },
    "Czechia": {
        "code": "cz",
        "flag_colors": ["#FFFFFF", "#D7141A", "#11457E"],
        "accent": "#FFD700",
        "flag_pattern": "two horizontal bands of white and red with blue chevron at hoist",
        "cultural_motifs": "Bohemian crystal facets, Art Nouveau Mucha-inspired flowing lines, Prague astronomical clock circles, Czech lion heraldic",
        "landmarks": "Prague Castle silhouette, Charles Bridge towers, Astronomical Clock",
        "jersey_pattern": "red with blue and white angular design, Czech lion crest",
        "retro_era": "1996",
        "retro_desc": "red with blue trim — Czechia's silver medal era, Nedvěd generation",
        "retro_colors": ["#D7141A", "#FFFFFF", "#11457E"],
        "avoid": "specific political references, Czechoslovakia nostalgia",
    },
    # ── CAF ─────────────────────────────────────────────────────────────────
    "Morocco": {
        "code": "ma",
        "flag_colors": ["#C1272D", "#006233"],
        "accent": "#FFD700",
        "flag_pattern": "red field with green pentacle star",
        "cultural_motifs": "Moorish zellige tile patterns, pentacle star geometry, medina archways, Atlas Mountain ridges, Berber carpet weave patterns",
        "landmarks": "Hassan II Mosque minaret, Marrakech medina gates, Atlas Mountains",
        "jersey_pattern": "red with green geometric Moorish tile pattern overlay, gold accents",
        "retro_era": "2022",
        "retro_desc": "red with green trim — the historic World Cup semifinal run that stunned the world",
        "retro_colors": ["#C1272D", "#006233", "#FFD700"],
        "avoid": "Islamic religious text or Quran quotes, Western Sahara political references",
    },
    "Senegal": {
        "code": "sn",
        "flag_colors": ["#00853F", "#FDEF42", "#E31B23"],
        "accent": "#FFFFFF",
        "flag_pattern": "vertical green-yellow-red tricolor with green star on yellow",
        "cultural_motifs": "Baobab tree silhouettes, Teranga hospitality sun, djembe drum shapes, lion of Senegal, West African textile patterns",
        "landmarks": "African Renaissance Monument silhouette, pink Lake Retba, baobab forests",
        "jersey_pattern": "white with green and yellow accents, lion crest, dynamic diagonal",
        "retro_era": "2002",
        "retro_desc": "white with green trim — the debut World Cup, beating France in the opener",
        "retro_colors": ["#FFFFFF", "#00853F", "#FDEF42"],
        "avoid": "colonial French references, specific tribal imagery without context",
    },
    "Ghana": {
        "code": "gh",
        "flag_colors": ["#CE1126", "#FCD116", "#006B3F"],
        "accent": "#000000",
        "flag_pattern": "horizontal red-gold-green bands with black star centered",
        "cultural_motifs": "Adinkra symbol patterns, Black Star of Africa, kente cloth woven geometry, Ashanti golden stool silhouette, cocoa pod shapes",
        "landmarks": "Cape Coast Castle silhouette, Volta Lake, Ashanti cultural sites",
        "jersey_pattern": "white with black star, kente-inspired geometric shoulder pattern",
        "retro_era": "2010",
        "retro_desc": "white with kente pattern — the Black Stars, one penalty from the semifinals",
        "retro_colors": ["#FFFFFF", "#000000", "#FCD116"],
        "avoid": "slave trade imagery, specific tribal/clan symbols without research",
    },
    "Algeria": {
        "code": "dz",
        "flag_colors": ["#006233", "#FFFFFF", "#D21034"],
        "accent": "#FFD700",
        "flag_pattern": "vertical green and white halves with red crescent and star",
        "cultural_motifs": "crescent and star arcs, Saharan sand dune curves, Casbah architectural geometry, Berber tattoo patterns, desert rose spirals",
        "landmarks": "Casbah of Algiers silhouette, Saharan dunes, Roman ruins",
        "jersey_pattern": "green and white halved, red crescent accent, desert-inspired",
        "retro_era": "2014",
        "retro_desc": "green with white trim — Algeria's best World Cup, round of 16 drama",
        "retro_colors": ["#006233", "#FFFFFF", "#D21034"],
        "avoid": "French colonial references, war of independence imagery",
    },
    "Cape Verde": {
        "code": "cv",
        "flag_colors": ["#003DA5", "#FFFFFF", "#CE1126", "#F7D116"],
        "accent": "#000000",
        "flag_pattern": "blue field with circle of ten yellow stars and red-white stripes",
        "cultural_motifs": "ten island stars in circle, Atlantic ocean waves, volcanic island peaks, morna music flow, maritime navigation patterns",
        "landmarks": "volcanic peaks, Atlantic coastline, Cidade Velha ruins",
        "jersey_pattern": "blue with yellow star circle, red and white band accents",
        "retro_era": "2026",
        "retro_desc": "historic first World Cup — blue ocean pride with golden stars",
        "retro_colors": ["#003DA5", "#F7D116", "#FFFFFF"],
        "avoid": "Portuguese colonial references, poverty imagery",
    },
    "DR Congo": {
        "code": "cd",
        "flag_colors": ["#007FFF", "#CE1021", "#F7D618"],
        "accent": "#FFFFFF",
        "flag_pattern": "sky blue field with diagonal red stripe bordered in yellow",
        "cultural_motifs": "Congo River flowing curves, Okapi silhouette, tropical forest canopy layers, traditional mask outlines, rumba rhythm spirals",
        "landmarks": "Congo River bends, tropical rainforest canopy, Kinshasa skyline",
        "jersey_pattern": "sky blue with diagonal red and yellow stripe, bold energy",
        "retro_era": "1974",
        "retro_desc": "green and yellow — Zaire's pioneering World Cup as first sub-Saharan African team",
        "retro_colors": ["#007FFF", "#CE1021", "#F7D618"],
        "avoid": "conflict minerals/war imagery, specific political references, colonial Belgian imagery",
    },
    "Egypt": {
        "code": "eg",
        "flag_colors": ["#CE1126", "#FFFFFF", "#000000"],
        "accent": "#C09E5F",
        "flag_pattern": "horizontal red-white-black triband with golden eagle",
        "cultural_motifs": "pyramid triangles, Eye of Horus, pharaoh headdress lines, Nile river curves, papyrus reed patterns, scarab wing forms",
        "landmarks": "Pyramids of Giza, Sphinx silhouette, Nile River bends",
        "jersey_pattern": "red with pharaonic golden collar pattern, black and white accents",
        "retro_era": "1990",
        "retro_desc": "red with white trim — Egypt at Italia 90, the Pharaohs return",
        "retro_colors": ["#CE1126", "#FFFFFF", "#000000"],
        "avoid": "specific religious text or symbols, Cleopatra/orientalist stereotypes",
    },
    "Ivory Coast": {
        "code": "ci",
        "flag_colors": ["#FF8200", "#FFFFFF", "#009A44"],
        "accent": "#000000",
        "flag_pattern": "vertical orange-white-green tricolor",
        "cultural_motifs": "elephant silhouette charging, Baoulé sun disc, cocoa leaf patterns, traditional mask outlines, West African textile geometry",
        "landmarks": "Basilica of Yamoussoukro dome, Abidjan skyline, tropical forests",
        "jersey_pattern": "orange with green trim, elephant crest, dynamic diagonal pattern",
        "retro_era": "2006",
        "retro_desc": "orange with white and green — Drogba's generation, the golden era",
        "retro_colors": ["#FF8200", "#FFFFFF", "#009A44"],
        "avoid": "conflict/civil war imagery, specific political references",
    },
    "South Africa": {
        "code": "za",
        "flag_colors": ["#007A4D", "#FFB612", "#000000", "#DE3831", "#002395", "#FFFFFF"],
        "accent": "#FFD700",
        "flag_pattern": "Y-shaped green band with black triangle, gold borders, red and blue panels",
        "cultural_motifs": "protea flower, springbok leap silhouette, Table Mountain flat top, rainbow nation color bands, Ndebele geometric patterns",
        "landmarks": "Table Mountain silhouette, Mandela Bridge, Cape of Good Hope",
        "jersey_pattern": "green and gold with Ndebele-inspired geometric pattern, bold Y-shape",
        "retro_era": "2010",
        "retro_desc": "green and gold — the host nation, Bafana Bafana's proudest moment",
        "retro_colors": ["#007A4D", "#FFB612", "#FFFFFF"],
        "avoid": "apartheid references, specific political imagery, racial division themes",
    },
    "Tunisia": {
        "code": "tn",
        "flag_colors": ["#E70013", "#FFFFFF"],
        "accent": "#000000",
        "flag_pattern": "red field with white circle containing red crescent and star",
        "cultural_motifs": "crescent and star arcs, Carthage ancient column outlines, Mediterranean wave patterns, mosaic tile geometry, olive branch curves",
        "landmarks": "Carthage ruins, Bardo Museum mosaics, Sidi Bou Said blue and white",
        "jersey_pattern": "red with white chest panel, crescent motif, clean Mediterranean lines",
        "retro_era": "2018",
        "retro_desc": "red with white — the Eagles of Carthage, North African pride",
        "retro_colors": ["#E70013", "#FFFFFF"],
        "avoid": "specific religious text, colonial French references",
    },
    # ── AFC ─────────────────────────────────────────────────────────────────
    "Japan": {
        "code": "jp",
        "flag_colors": ["#FFFFFF", "#BC002D"],
        "accent": "#000000",
        "flag_pattern": "white field with red circle (Hinomaru)",
        "cultural_motifs": "rising sun disc radiating, cherry blossom scatter, wave patterns (Hokusai-inspired), samurai armor angles, origami crane folds, torii gate silhouette",
        "landmarks": "Mount Fuji silhouette, torii gate, Shibuya crossing, Tokyo Tower",
        "jersey_pattern": "samurai blue with origami-inspired angular pattern, white accents",
        "retro_era": "2002",
        "retro_desc": "blue with flame pattern — co-hosting the World Cup, the Blue Samurai's finest hour",
        "retro_colors": ["#002FA7", "#FFFFFF", "#BC002D"],
        "avoid": "Imperial Rising Sun flag (military version with rays), specific anime characters, ninja stereotypes",
    },
    "South Korea": {
        "code": "kr",
        "flag_colors": ["#FFFFFF", "#CD2E3A", "#0047A0", "#000000"],
        "accent": "#FFD700",
        "flag_pattern": "white field with red and blue Taeguk and four black trigrams",
        "cultural_motifs": "Taeguk yin-yang swirl, trigram line patterns, tiger silhouette leaping, hanbok fabric curves, DMZ barrier-breaking energy",
        "landmarks": "Gyeongbokgung palace, Seoul skyline, Korean temple gates",
        "jersey_pattern": "red with Taeguk-inspired swirl pattern, blue and black accents",
        "retro_era": "2002",
        "retro_desc": "red with gold trim — the Red Devils, semifinal miracle on home soil",
        "retro_colors": ["#CD2E3A", "#FFD700", "#FFFFFF"],
        "avoid": "North Korea references, specific K-pop branding, DMZ political imagery",
    },
    "Australia": {
        "code": "au",
        "flag_colors": ["#00008B", "#FFD700", "#FFFFFF"],
        "accent": "#008000",
        "flag_pattern": "dark blue field with Southern Cross stars and Commonwealth Star",
        "cultural_motifs": "kangaroo leap silhouette, Southern Cross constellation, boomerang curves, Aboriginal dot-art inspired patterns, coral reef forms",
        "landmarks": "Sydney Opera House sails, Uluru silhouette, Great Barrier Reef",
        "jersey_pattern": "gold with green trim, kangaroo crest, Southern Cross accent",
        "retro_era": "2006",
        "retro_desc": "gold and green — the Socceroos' breakthrough, Cahill's volley era",
        "retro_colors": ["#FFD700", "#008000", "#FFFFFF"],
        "avoid": "Aboriginal sacred site imagery (Uluru) without cultural respect, colonial British imagery",
    },
    "Saudi Arabia": {
        "code": "sa",
        "flag_colors": ["#006C35", "#FFFFFF"],
        "accent": "#FFD700",
        "flag_pattern": "green field with white Arabic shahada inscription and sword",
        "cultural_motifs": "palm tree and crossed swords crest, desert dune curves, falcon wing spread, geometric Islamic art patterns (non-religious), sand rose formations",
        "landmarks": "Kingdom Tower silhouette, desert dunes, oasis palm groves",
        "jersey_pattern": "green with white geometric pattern, gold falcon crest accent",
        "retro_era": "1994",
        "retro_desc": "green and white — Al-Owairan's wonder goal, Saudi football's peak",
        "retro_colors": ["#006C35", "#FFFFFF"],
        "avoid": "shahada text (Islamic creed — NEVER reproduce), sword imagery referencing violence, religious text of any kind",
    },
    "Iran": {
        "code": "ir",
        "flag_colors": ["#239F40", "#FFFFFF", "#DA0000"],
        "accent": "#FFD700",
        "flag_pattern": "horizontal green-white-red triband with red emblem",
        "cultural_motifs": "Persian carpet geometry, cheetah silhouette (Asiatic), Persepolis column capitals, calligraphic swoops, pomegranate forms",
        "landmarks": "Persepolis ruins, Isfahan bridges, desert mountain ridges",
        "jersey_pattern": "white with red and green accents, Persian carpet-inspired geometric overlay",
        "retro_era": "1998",
        "retro_desc": "white with green and red — Team Melli, the historic victory over USA",
        "retro_colors": ["#FFFFFF", "#239F40", "#DA0000"],
        "avoid": "specific political regime imagery, nuclear references, protest imagery",
    },
    "Iraq": {
        "code": "iq",
        "flag_colors": ["#CE1126", "#FFFFFF", "#007A3D", "#000000"],
        "accent": "#FFD700",
        "flag_pattern": "horizontal red-white-black triband with green text",
        "cultural_motifs": "Mesopotamian ziggurat steps, Ishtar Gate lion relief, Tigris-Euphrates river curves, date palm fronds, cuneiform-inspired geometric marks",
        "landmarks": "Spiral Minaret of Samarra, Ishtar Gate outline, Mesopotamian arches",
        "jersey_pattern": "white with green sash, red and black accents, Mesopotamian pattern",
        "retro_era": "1986",
        "retro_desc": "white and green — Iraq's World Cup debut in Mexico",
        "retro_colors": ["#FFFFFF", "#007A3D", "#CE1126"],
        "avoid": "war/conflict imagery, specific political regime symbols, religious text",
    },
    "Jordan": {
        "code": "jo",
        "flag_colors": ["#000000", "#FFFFFF", "#007A3D", "#CE1126"],
        "accent": "#FFD700",
        "flag_pattern": "horizontal black-white-green triband with red chevron and white star",
        "cultural_motifs": "Petra treasury facade outline, desert canyon walls, seven-pointed star, Bedouin tent curves, Dead Sea mineral crystalline patterns",
        "landmarks": "Petra treasury silhouette, Wadi Rum desert arches, Dead Sea coast",
        "jersey_pattern": "white with red chevron, green and black accents, desert-inspired",
        "retro_era": "2026",
        "retro_desc": "historic first World Cup — red, black, white and green, the Nashama's moment",
        "retro_colors": ["#CE1126", "#FFFFFF", "#000000", "#007A3D"],
        "avoid": "specific religious site imagery (Al-Aqsa), political conflict references",
    },
    "Qatar": {
        "code": "qa",
        "flag_colors": ["#8A1538", "#FFFFFF"],
        "accent": "#FFD700",
        "flag_pattern": "maroon field with white serrated band on hoist side",
        "cultural_motifs": "dhow sail curves, falcon silhouette, pearl diving descent, nine-pointed serrated edge, sand dune ridges, futuristic skyline angles",
        "landmarks": "Museum of Islamic Art, Souq Waqif arches, Doha skyline towers",
        "jersey_pattern": "maroon with white serrated edge pattern, gold accents",
        "retro_era": "2022",
        "retro_desc": "maroon and white — the host nation, Al-Annabi's debut",
        "retro_colors": ["#8A1538", "#FFFFFF"],
        "avoid": "labor controversy references, specific political imagery",
    },
    "Uzbekistan": {
        "code": "uz",
        "flag_colors": ["#0099B5", "#CE1126", "#FFFFFF", "#1EB53A"],
        "accent": "#FFD700",
        "flag_pattern": "horizontal blue-white-green bands with red fimbriations and crescent and stars",
        "cultural_motifs": "Silk Road caravan silhouettes, Registan madrasa arches, crescent and twelve stars, cotton plant forms, Islamic geometric tile (non-religious), Timurid architecture patterns",
        "landmarks": "Registan Square, Silk Road cities, Samarkand domes",
        "jersey_pattern": "white with blue and green accents, Silk Road-inspired geometric pattern",
        "retro_era": "2026",
        "retro_desc": "historic first World Cup — blue, white and green, the White Wolves arrive",
        "retro_colors": ["#0099B5", "#FFFFFF", "#1EB53A"],
        "avoid": "Soviet-era imagery, specific religious text, cotton harvest forced labor references",
    },
    # ── OFC ─────────────────────────────────────────────────────────────────
    "New Zealand": {
        "code": "nz",
        "flag_colors": ["#00247D", "#CC142B", "#FFFFFF"],
        "accent": "#000000",
        "flag_pattern": "blue ensign with four red stars of Southern Cross",
        "cultural_motifs": "silver fern frond unfurling, koru Maori spiral, All Whites football energy, Southern Cross stars, mountain peak ridges, wave forms",
        "landmarks": "Sky Tower silhouette, Mount Cook, Milford Sound fjord walls",
        "jersey_pattern": "all white with silver fern, black accents, clean Kiwi design",
        "retro_era": "2010",
        "retro_desc": "all white — the All Whites, unbeaten in South Africa with three draws",
        "retro_colors": ["#FFFFFF", "#000000"],
        "avoid": "Aboriginal/Maori sacred symbols without cultural context, specific haka references",
    },
}

# ── Tier assignments for generation priority ──────────────────────────────
TIER_1 = [
    "USA", "Mexico", "Canada", "Brazil", "Argentina", "Germany", "England",
    "France", "Spain", "Portugal", "Colombia", "Japan", "South Korea",
    "Morocco", "Netherlands", "Italy",  # Italy not in WC but high demand
]

TIER_2 = [n for n in NATIONS if n not in TIER_1]

ALL_NATION_NAMES = list(NATIONS.keys())
