#!/usr/bin/env python3
"""
Mexico Video Reel Builder
=========================
Creates a 9:16 vertical video reel (~20s) from still images with
Ken Burns zoom/pan effects, crossfade transitions, and background music.

Sequence:
  1. Anchor image (cinematic car shot) — 4s
  2. Store screengrab (hooddshop.com) — 3s
  3. Mexico Home design — 3s
  4. Mexico Away design — 3s
  5. Mexico Flag design — 3s
  6. CTA Endcard — 5s

Usage:
    pip install moviepy Pillow numpy
    python create_reel.py

    # With custom music:
    python create_reel.py --music "path/to/track.mp3"

    # Skip store screenshot (if you don't have one yet):
    python create_reel.py --no-store

Notes:
    - If moviepy isn't available, falls back to ffmpeg directly
    - ffmpeg must be on PATH (moviepy needs it too)
    - Output: mexico_reel_9x16.mp4
"""
import sys
import os
import argparse
import subprocess
import tempfile
import shutil
from pathlib import Path

# Fix Windows encoding
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# ── Config ──────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent
OUTPUT_VIDEO = SCRIPT_DIR / "mexico_reel_9x16.mp4"

# Target dimensions (9:16 vertical)
TARGET_W = 1080
TARGET_H = 1920
FPS = 30

# Frame sequence: (filename, duration_seconds, label)
FRAME_SEQUENCE = [
    ("meetup_cinematic_sedan_gemini_1777472314.png", 4.0, "anchor"),
    ("hooddshop_store.png", 3.0, "store"),       # Optional — skipped if missing
    ("Mexico_home.png", 3.0, "design_home"),
    ("Mexico_away.png", 3.0, "design_away"),
    ("Mexico_flag.png", 3.0, "design_flag"),
    ("endcard_mx_v1.png", 5.0, "endcard"),        # Generated by create_endcard_mexico.py
]

CROSSFADE_DURATION = 0.5  # seconds of crossfade between slides


def check_ffmpeg():
    """Check if ffmpeg is available."""
    try:
        result = subprocess.run(["ffmpeg", "-version"], capture_output=True, text=True, timeout=5)
        return result.returncode == 0
    except Exception:
        return False


def prepare_frame(img_path, target_w, target_h):
    """Resize/crop an image to fit target dimensions (center crop with fill)."""
    from PIL import Image

    img = Image.open(img_path).convert("RGB")
    iw, ih = img.size

    # Calculate scale to fill target (cover, not contain)
    scale = max(target_w / iw, target_h / ih)
    new_w = int(iw * scale)
    new_h = int(ih * scale)

    img = img.resize((new_w, new_h), Image.LANCZOS)

    # Center crop to exact target
    left = (new_w - target_w) // 2
    top = (new_h - target_h) // 2
    img = img.crop((left, top, left + target_w, top + target_h))

    return img


def prepare_design_frame(img_path, target_w, target_h):
    """For flat design images: place on dark background with padding, preserving aspect ratio."""
    from PIL import Image, ImageDraw

    # Create dark background
    bg = Image.new("RGB", (target_w, target_h), (15, 15, 15))

    # Load and resize design to fit with padding
    design = Image.open(img_path).convert("RGB")
    dw, dh = design.size

    # Use 85% of width, maintain aspect ratio
    max_w = int(target_w * 0.85)
    max_h = int(target_h * 0.55)  # Leave room for breathing
    scale = min(max_w / dw, max_h / dh)
    new_w = int(dw * scale)
    new_h = int(dh * scale)
    design = design.resize((new_w, new_h), Image.LANCZOS)

    # Center on background
    x = (target_w - new_w) // 2
    y = (target_h - new_h) // 2

    # Add subtle shadow behind design
    shadow = Image.new("RGB", (new_w + 20, new_h + 20), (8, 8, 8))
    bg.paste(shadow, (x + 10, y + 10))
    bg.paste(design, (x, y))

    return bg


def build_with_moviepy(frames, music_path=None):
    """Build video using moviepy (preferred method)."""
    try:
        from moviepy import ImageClip, concatenate_videoclips, CompositeVideoClip
        from moviepy import AudioFileClip
    except ImportError:
        try:
            from moviepy.editor import ImageClip, concatenate_videoclips, CompositeVideoClip, AudioFileClip
        except ImportError:
            print("[ERROR] moviepy not found. Install: pip install moviepy")
            return False

    import numpy as np

    clips = []
    for img_path, duration, label in frames:
        print(f"  [CLIP] {label}: {img_path.name} ({duration}s)")

        # Prepare the image based on type
        if label.startswith("design_"):
            pil_img = prepare_design_frame(img_path, TARGET_W, TARGET_H)
        else:
            pil_img = prepare_frame(img_path, TARGET_W, TARGET_H)

        # Convert to numpy array for moviepy
        frame_array = np.array(pil_img)

        clip = ImageClip(frame_array).with_duration(duration)
        clips.append(clip)

    # Add crossfade transitions
    if len(clips) > 1:
        print(f"  [TRANSITION] Adding {CROSSFADE_DURATION}s crossfades...")
        final_clips = [clips[0]]
        for i in range(1, len(clips)):
            clips[i] = clips[i].with_start(
                sum(f[1] for f in frames[:i]) - CROSSFADE_DURATION * i
            ).crossfadein(CROSSFADE_DURATION)
            final_clips.append(clips[i])

        video = CompositeVideoClip(final_clips)
    else:
        video = clips[0]

    # Add audio if provided
    if music_path and Path(music_path).exists():
        print(f"  [AUDIO] Adding music: {music_path}")
        try:
            audio = AudioFileClip(str(music_path))
            # Trim audio to video duration, fade out last 2s
            audio = audio.subclipped(0, min(audio.duration, video.duration))
            audio = audio.audio_fadeout(2.0)
            video = video.with_audio(audio)
        except Exception as e:
            print(f"  [WARN] Could not add audio: {e}")

    # Export
    print(f"  [EXPORT] Rendering {TARGET_W}x{TARGET_H} @ {FPS}fps...")
    video.write_videofile(
        str(OUTPUT_VIDEO),
        fps=FPS,
        codec="libx264",
        audio_codec="aac" if music_path else None,
        preset="medium",
        bitrate="8000k",
        logger="bar",
    )

    size_mb = OUTPUT_VIDEO.stat().st_size / (1024 * 1024)
    print(f"  [OK] Saved: {OUTPUT_VIDEO} ({size_mb:.1f}MB)")
    return True


def build_with_ffmpeg(frames, music_path=None):
    """Build video using ffmpeg directly (fallback method)."""
    from PIL import Image

    print("  [FFMPEG] Using ffmpeg directly (moviepy not available)...")

    # Create temp directory for prepared frames
    tmp_dir = Path(tempfile.mkdtemp(prefix="hoodd_reel_"))
    print(f"  [TEMP] Working in: {tmp_dir}")

    try:
        # Prepare individual frame images and a concat file
        concat_entries = []
        for idx, (img_path, duration, label) in enumerate(frames):
            print(f"  [FRAME] {label}: {img_path.name} ({duration}s)")

            if label.startswith("design_"):
                pil_img = prepare_design_frame(img_path, TARGET_W, TARGET_H)
            else:
                pil_img = prepare_frame(img_path, TARGET_W, TARGET_H)

            frame_path = tmp_dir / f"frame_{idx:02d}.png"
            pil_img.save(str(frame_path), "PNG")
            concat_entries.append((frame_path, duration))

        # Create individual clips and concat
        clip_paths = []
        for idx, (frame_path, duration) in enumerate(concat_entries):
            clip_path = tmp_dir / f"clip_{idx:02d}.mp4"
            cmd = [
                "ffmpeg", "-y",
                "-loop", "1",
                "-i", str(frame_path),
                "-c:v", "libx264",
                "-t", str(duration),
                "-pix_fmt", "yuv420p",
                "-vf", f"scale={TARGET_W}:{TARGET_H},fps={FPS}",
                "-preset", "ultrafast",
                "-tune", "stillimage",
                "-crf", "20",
                str(clip_path),
            ]
            print(f"    [ENCODE] clip_{idx:02d} ({duration}s)...")
            subprocess.run(cmd, capture_output=True, timeout=300)
            clip_paths.append(clip_path)

        # Create concat file
        concat_file = tmp_dir / "concat.txt"
        with open(concat_file, "w") as f:
            for cp in clip_paths:
                f.write(f"file '{cp}'\n")

        # Concat all clips with optional audio
        concat_output = tmp_dir / "concat_raw.mp4"
        has_audio = music_path and Path(music_path).exists()

        # Build ffmpeg command — all inputs first, then options, then output
        cmd = ["ffmpeg", "-y"]

        # Input 0: video from concat
        cmd.extend(["-f", "concat", "-safe", "0", "-i", str(concat_file)])

        # Input 1: audio (if provided)
        if has_audio:
            cmd.extend(["-i", str(music_path)])

        # Stream mapping
        cmd.extend(["-map", "0:v"])
        if has_audio:
            cmd.extend(["-map", "1:a"])

        # Video codec
        cmd.extend([
            "-c:v", "libx264",
            "-pix_fmt", "yuv420p",
            "-preset", "medium",
            "-crf", "18",
        ])

        # Audio codec
        if has_audio:
            cmd.extend(["-c:a", "aac", "-b:a", "192k", "-shortest"])

        cmd.append(str(OUTPUT_VIDEO))

        print(f"  [CONCAT] Merging {len(clip_paths)} clips...")
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        if result.returncode != 0:
            print(f"  [ERROR] ffmpeg concat failed:\n{result.stderr[:500]}")
            return False

        size_mb = OUTPUT_VIDEO.stat().st_size / (1024 * 1024)
        print(f"  [OK] Saved: {OUTPUT_VIDEO} ({size_mb:.1f}MB)")
        return True

    finally:
        # Clean up temp files
        shutil.rmtree(tmp_dir, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser(description="Create Mexico video reel")
    parser.add_argument("--music", type=str, default=None,
                        help="Path to background music file (MP3/WAV)")
    parser.add_argument("--no-store", action="store_true",
                        help="Skip store screenshot frame (if you don't have one)")
    parser.add_argument("--output", "-o", type=str, default=None,
                        help="Output filename (default: mexico_reel_9x16.mp4)")
    args = parser.parse_args()

    # Allow custom output filename
    global OUTPUT_VIDEO
    if args.output:
        OUTPUT_VIDEO = SCRIPT_DIR / args.output

    print(f"Hood'd Mexico Reel Builder")
    print(f"{'='*50}")
    print(f"  Output: {OUTPUT_VIDEO}")
    print(f"  Size:   {TARGET_W}x{TARGET_H} @ {FPS}fps")
    print(f"  Music:  {args.music or 'None (silent)'}")

    # Validate frame files
    valid_frames = []
    for filename, duration, label in FRAME_SEQUENCE:
        path = SCRIPT_DIR / filename
        if not path.exists():
            if label == "store" and args.no_store:
                print(f"  [SKIP] {filename} (--no-store)")
                continue
            elif label == "store":
                print(f"  [SKIP] {filename} (not found — use --no-store or add a screenshot)")
                continue
            elif label == "endcard" and not path.exists():
                # Try to generate it
                print(f"  [INFO] Endcard not found, attempting to generate...")
                try:
                    from create_endcard_mexico import create_endcard
                    create_endcard()
                except Exception as e:
                    print(f"  [ERROR] Could not generate endcard: {e}")
                    print(f"  [INFO] Run 'python create_endcard_mexico.py' first")
                    continue
                if not path.exists():
                    print(f"  [SKIP] {filename} (generation failed)")
                    continue
            else:
                print(f"  [ERROR] Missing: {filename}")
                sys.exit(1)

        valid_frames.append((path, duration, label))

    if len(valid_frames) < 2:
        print(f"[ERROR] Need at least 2 frames to build a reel")
        sys.exit(1)

    total_duration = sum(f[1] for f in valid_frames)
    print(f"  Frames: {len(valid_frames)}")
    print(f"  Duration: ~{total_duration:.0f}s")
    print(f"{'='*50}\n")

    # Check for ffmpeg
    if not check_ffmpeg():
        print("[ERROR] ffmpeg not found on PATH. Please install ffmpeg:")
        print("  Windows: winget install ffmpeg")
        print("  Or download from: https://ffmpeg.org/download.html")
        sys.exit(1)

    # Try moviepy first, fall back to ffmpeg
    try:
        import moviepy
        print("[ENGINE] Using moviepy")
        success = build_with_moviepy(valid_frames, args.music)
    except ImportError:
        print("[ENGINE] moviepy not available, using ffmpeg directly")
        success = build_with_ffmpeg(valid_frames, args.music)

    if success:
        print(f"\n[DONE] Reel saved to: {OUTPUT_VIDEO}")
        print(f"  Upload to: Instagram Reels, TikTok, Facebook Reels")
    else:
        print(f"\n[FAIL] Could not create reel")
        sys.exit(1)


if __name__ == "__main__":
    main()
